//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismUnityApp2.MobileService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/VaksMobileService")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime MessageTimeField;
        
        private string messagedataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MessageTime {
            get {
                return this.MessageTimeField;
            }
            set {
                if ((this.MessageTimeField.Equals(value) != true)) {
                    this.MessageTimeField = value;
                    this.RaisePropertyChanged("MessageTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string messagedata {
            get {
                return this.messagedataField;
            }
            set {
                if ((object.ReferenceEquals(this.messagedataField, value) != true)) {
                    this.messagedataField = value;
                    this.RaisePropertyChanged("messagedata");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Toemning", Namespace="http://schemas.datacontract.org/2004/07/VaksMobileService")]
    public partial class Toemning : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FraktionField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private int ToemmeIdField;
        
        private string TypeField;
        
        private string WeightField;
        
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fraktion {
            get {
                return this.FraktionField;
            }
            set {
                if ((object.ReferenceEquals(this.FraktionField, value) != true)) {
                    this.FraktionField = value;
                    this.RaisePropertyChanged("Fraktion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToemmeId {
            get {
                return this.ToemmeIdField;
            }
            set {
                if ((this.ToemmeIdField.Equals(value) != true)) {
                    this.ToemmeIdField = value;
                    this.RaisePropertyChanged("ToemmeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightField, value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessData", Namespace="http://schemas.datacontract.org/2004/07/VaksMobileService")]
    public partial class AccessData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FraktionField;
        
        private int ToemmeIdField;
        
        private string typeField;
        
        private string weightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fraktion {
            get {
                return this.FraktionField;
            }
            set {
                if ((object.ReferenceEquals(this.FraktionField, value) != true)) {
                    this.FraktionField = value;
                    this.RaisePropertyChanged("Fraktion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToemmeId {
            get {
                return this.ToemmeIdField;
            }
            set {
                if ((this.ToemmeIdField.Equals(value) != true)) {
                    this.ToemmeIdField = value;
                    this.RaisePropertyChanged("ToemmeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight {
            get {
                return this.weightField;
            }
            set {
                if ((object.ReferenceEquals(this.weightField, value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MobileService.IVaksService")]
    public interface IVaksService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IVaksService/GetData", ReplyAction="http://tempuri.org/IVaksService/GetDataResponse")]
        System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState);
        
        string EndGetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IVaksService/GetMessageDatas", ReplyAction="http://tempuri.org/IVaksService/GetMessageDatasResponse")]
        System.IAsyncResult BeginGetMessageDatas(string Latitude, string Longitude, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Message> EndGetMessageDatas(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IVaksService/GetToemmeDatas", ReplyAction="http://tempuri.org/IVaksService/GetToemmeDatasResponse")]
        System.IAsyncResult BeginGetToemmeDatas(PrismUnityApp2.MobileService.Toemning toemning, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> EndGetToemmeDatas(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IVaksService/GetToemmeDatasByPladsId", ReplyAction="http://tempuri.org/IVaksService/GetToemmeDatasByPladsIdResponse")]
        System.IAsyncResult BeginGetToemmeDatasByPladsId(int GbsId, System.DateTime date, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> EndGetToemmeDatasByPladsId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IVaksService/LoginAndReturnPladsId", ReplyAction="http://tempuri.org/IVaksService/LoginAndReturnPladsIdResponse")]
        System.IAsyncResult BeginLoginAndReturnPladsId(string UserName, string Password, double Latitude, double Longitude, System.AsyncCallback callback, object asyncState);
        
        PrismUnityApp2.MobileService.AccessData EndLoginAndReturnPladsId(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVaksServiceChannel : PrismUnityApp2.MobileService.IVaksService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMessageDatasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMessageDatasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Message> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Message>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetToemmeDatasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetToemmeDatasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetToemmeDatasByPladsIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetToemmeDatasByPladsIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginAndReturnPladsIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginAndReturnPladsIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PrismUnityApp2.MobileService.AccessData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PrismUnityApp2.MobileService.AccessData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VaksServiceClient : System.ServiceModel.ClientBase<PrismUnityApp2.MobileService.IVaksService>, PrismUnityApp2.MobileService.IVaksService {
        
        private BeginOperationDelegate onBeginGetDataDelegate;
        
        private EndOperationDelegate onEndGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMessageDatasDelegate;
        
        private EndOperationDelegate onEndGetMessageDatasDelegate;
        
        private System.Threading.SendOrPostCallback onGetMessageDatasCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetToemmeDatasDelegate;
        
        private EndOperationDelegate onEndGetToemmeDatasDelegate;
        
        private System.Threading.SendOrPostCallback onGetToemmeDatasCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetToemmeDatasByPladsIdDelegate;
        
        private EndOperationDelegate onEndGetToemmeDatasByPladsIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetToemmeDatasByPladsIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginAndReturnPladsIdDelegate;
        
        private EndOperationDelegate onEndLoginAndReturnPladsIdDelegate;
        
        private System.Threading.SendOrPostCallback onLoginAndReturnPladsIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public VaksServiceClient() : 
                base(VaksServiceClient.GetDefaultBinding(), VaksServiceClient.GetDefaultEndpointAddress()) {
        }
        
        public VaksServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VaksServiceClient.GetBindingForEndpoint(endpointConfiguration), VaksServiceClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public VaksServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VaksServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public VaksServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VaksServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public VaksServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
        
        public event System.EventHandler<GetMessageDatasCompletedEventArgs> GetMessageDatasCompleted;
        
        public event System.EventHandler<GetToemmeDatasCompletedEventArgs> GetToemmeDatasCompleted;
        
        public event System.EventHandler<GetToemmeDatasByPladsIdCompletedEventArgs> GetToemmeDatasByPladsIdCompleted;
        
        public event System.EventHandler<LoginAndReturnPladsIdCompletedEventArgs> LoginAndReturnPladsIdCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PrismUnityApp2.MobileService.IVaksService.BeginGetData(int value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PrismUnityApp2.MobileService.IVaksService.EndGetData(System.IAsyncResult result) {
            return base.Channel.EndGetData(result);
        }
        
        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int value = ((int)(inValues[0]));
            return ((PrismUnityApp2.MobileService.IVaksService)(this)).BeginGetData(value, callback, asyncState);
        }
        
        private object[] OnEndGetData(System.IAsyncResult result) {
            string retVal = ((PrismUnityApp2.MobileService.IVaksService)(this)).EndGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataCompleted(object state) {
            if ((this.GetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataAsync(int value) {
            this.GetDataAsync(value, null);
        }
        
        public void GetDataAsync(int value, object userState) {
            if ((this.onBeginGetDataDelegate == null)) {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null)) {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null)) {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                        value}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PrismUnityApp2.MobileService.IVaksService.BeginGetMessageDatas(string Latitude, string Longitude, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMessageDatas(Latitude, Longitude, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Message> PrismUnityApp2.MobileService.IVaksService.EndGetMessageDatas(System.IAsyncResult result) {
            return base.Channel.EndGetMessageDatas(result);
        }
        
        private System.IAsyncResult OnBeginGetMessageDatas(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Latitude = ((string)(inValues[0]));
            string Longitude = ((string)(inValues[1]));
            return ((PrismUnityApp2.MobileService.IVaksService)(this)).BeginGetMessageDatas(Latitude, Longitude, callback, asyncState);
        }
        
        private object[] OnEndGetMessageDatas(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Message> retVal = ((PrismUnityApp2.MobileService.IVaksService)(this)).EndGetMessageDatas(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMessageDatasCompleted(object state) {
            if ((this.GetMessageDatasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMessageDatasCompleted(this, new GetMessageDatasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMessageDatasAsync(string Latitude, string Longitude) {
            this.GetMessageDatasAsync(Latitude, Longitude, null);
        }
        
        public void GetMessageDatasAsync(string Latitude, string Longitude, object userState) {
            if ((this.onBeginGetMessageDatasDelegate == null)) {
                this.onBeginGetMessageDatasDelegate = new BeginOperationDelegate(this.OnBeginGetMessageDatas);
            }
            if ((this.onEndGetMessageDatasDelegate == null)) {
                this.onEndGetMessageDatasDelegate = new EndOperationDelegate(this.OnEndGetMessageDatas);
            }
            if ((this.onGetMessageDatasCompletedDelegate == null)) {
                this.onGetMessageDatasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMessageDatasCompleted);
            }
            base.InvokeAsync(this.onBeginGetMessageDatasDelegate, new object[] {
                        Latitude,
                        Longitude}, this.onEndGetMessageDatasDelegate, this.onGetMessageDatasCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PrismUnityApp2.MobileService.IVaksService.BeginGetToemmeDatas(PrismUnityApp2.MobileService.Toemning toemning, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetToemmeDatas(toemning, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> PrismUnityApp2.MobileService.IVaksService.EndGetToemmeDatas(System.IAsyncResult result) {
            return base.Channel.EndGetToemmeDatas(result);
        }
        
        private System.IAsyncResult OnBeginGetToemmeDatas(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PrismUnityApp2.MobileService.Toemning toemning = ((PrismUnityApp2.MobileService.Toemning)(inValues[0]));
            return ((PrismUnityApp2.MobileService.IVaksService)(this)).BeginGetToemmeDatas(toemning, callback, asyncState);
        }
        
        private object[] OnEndGetToemmeDatas(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> retVal = ((PrismUnityApp2.MobileService.IVaksService)(this)).EndGetToemmeDatas(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetToemmeDatasCompleted(object state) {
            if ((this.GetToemmeDatasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetToemmeDatasCompleted(this, new GetToemmeDatasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetToemmeDatasAsync(PrismUnityApp2.MobileService.Toemning toemning) {
            this.GetToemmeDatasAsync(toemning, null);
        }
        
        public void GetToemmeDatasAsync(PrismUnityApp2.MobileService.Toemning toemning, object userState) {
            if ((this.onBeginGetToemmeDatasDelegate == null)) {
                this.onBeginGetToemmeDatasDelegate = new BeginOperationDelegate(this.OnBeginGetToemmeDatas);
            }
            if ((this.onEndGetToemmeDatasDelegate == null)) {
                this.onEndGetToemmeDatasDelegate = new EndOperationDelegate(this.OnEndGetToemmeDatas);
            }
            if ((this.onGetToemmeDatasCompletedDelegate == null)) {
                this.onGetToemmeDatasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetToemmeDatasCompleted);
            }
            base.InvokeAsync(this.onBeginGetToemmeDatasDelegate, new object[] {
                        toemning}, this.onEndGetToemmeDatasDelegate, this.onGetToemmeDatasCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PrismUnityApp2.MobileService.IVaksService.BeginGetToemmeDatasByPladsId(int GbsId, System.DateTime date, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetToemmeDatasByPladsId(GbsId, date, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> PrismUnityApp2.MobileService.IVaksService.EndGetToemmeDatasByPladsId(System.IAsyncResult result) {
            return base.Channel.EndGetToemmeDatasByPladsId(result);
        }
        
        private System.IAsyncResult OnBeginGetToemmeDatasByPladsId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int GbsId = ((int)(inValues[0]));
            System.DateTime date = ((System.DateTime)(inValues[1]));
            return ((PrismUnityApp2.MobileService.IVaksService)(this)).BeginGetToemmeDatasByPladsId(GbsId, date, callback, asyncState);
        }
        
        private object[] OnEndGetToemmeDatasByPladsId(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> retVal = ((PrismUnityApp2.MobileService.IVaksService)(this)).EndGetToemmeDatasByPladsId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetToemmeDatasByPladsIdCompleted(object state) {
            if ((this.GetToemmeDatasByPladsIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetToemmeDatasByPladsIdCompleted(this, new GetToemmeDatasByPladsIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetToemmeDatasByPladsIdAsync(int GbsId, System.DateTime date) {
            this.GetToemmeDatasByPladsIdAsync(GbsId, date, null);
        }
        
        public void GetToemmeDatasByPladsIdAsync(int GbsId, System.DateTime date, object userState) {
            if ((this.onBeginGetToemmeDatasByPladsIdDelegate == null)) {
                this.onBeginGetToemmeDatasByPladsIdDelegate = new BeginOperationDelegate(this.OnBeginGetToemmeDatasByPladsId);
            }
            if ((this.onEndGetToemmeDatasByPladsIdDelegate == null)) {
                this.onEndGetToemmeDatasByPladsIdDelegate = new EndOperationDelegate(this.OnEndGetToemmeDatasByPladsId);
            }
            if ((this.onGetToemmeDatasByPladsIdCompletedDelegate == null)) {
                this.onGetToemmeDatasByPladsIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetToemmeDatasByPladsIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetToemmeDatasByPladsIdDelegate, new object[] {
                        GbsId,
                        date}, this.onEndGetToemmeDatasByPladsIdDelegate, this.onGetToemmeDatasByPladsIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PrismUnityApp2.MobileService.IVaksService.BeginLoginAndReturnPladsId(string UserName, string Password, double Latitude, double Longitude, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoginAndReturnPladsId(UserName, Password, Latitude, Longitude, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrismUnityApp2.MobileService.AccessData PrismUnityApp2.MobileService.IVaksService.EndLoginAndReturnPladsId(System.IAsyncResult result) {
            return base.Channel.EndLoginAndReturnPladsId(result);
        }
        
        private System.IAsyncResult OnBeginLoginAndReturnPladsId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string UserName = ((string)(inValues[0]));
            string Password = ((string)(inValues[1]));
            double Latitude = ((double)(inValues[2]));
            double Longitude = ((double)(inValues[3]));
            return ((PrismUnityApp2.MobileService.IVaksService)(this)).BeginLoginAndReturnPladsId(UserName, Password, Latitude, Longitude, callback, asyncState);
        }
        
        private object[] OnEndLoginAndReturnPladsId(System.IAsyncResult result) {
            PrismUnityApp2.MobileService.AccessData retVal = ((PrismUnityApp2.MobileService.IVaksService)(this)).EndLoginAndReturnPladsId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginAndReturnPladsIdCompleted(object state) {
            if ((this.LoginAndReturnPladsIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginAndReturnPladsIdCompleted(this, new LoginAndReturnPladsIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAndReturnPladsIdAsync(string UserName, string Password, double Latitude, double Longitude) {
            this.LoginAndReturnPladsIdAsync(UserName, Password, Latitude, Longitude, null);
        }
        
        public void LoginAndReturnPladsIdAsync(string UserName, string Password, double Latitude, double Longitude, object userState) {
            if ((this.onBeginLoginAndReturnPladsIdDelegate == null)) {
                this.onBeginLoginAndReturnPladsIdDelegate = new BeginOperationDelegate(this.OnBeginLoginAndReturnPladsId);
            }
            if ((this.onEndLoginAndReturnPladsIdDelegate == null)) {
                this.onEndLoginAndReturnPladsIdDelegate = new EndOperationDelegate(this.OnEndLoginAndReturnPladsId);
            }
            if ((this.onLoginAndReturnPladsIdCompletedDelegate == null)) {
                this.onLoginAndReturnPladsIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginAndReturnPladsIdCompleted);
            }
            base.InvokeAsync(this.onBeginLoginAndReturnPladsIdDelegate, new object[] {
                        UserName,
                        Password,
                        Latitude,
                        Longitude}, this.onEndLoginAndReturnPladsIdDelegate, this.onLoginAndReturnPladsIdCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PrismUnityApp2.MobileService.IVaksService CreateChannel() {
            return new VaksServiceClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVaksService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVaksService)) {
                return new System.ServiceModel.EndpointAddress("http://vf-kssweb2/Vaks2Svc/VaksService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return VaksServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IVaksService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return VaksServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IVaksService);
        }
        
        private class VaksServiceClientChannel : ChannelBase<PrismUnityApp2.MobileService.IVaksService>, PrismUnityApp2.MobileService.IVaksService {
            
            public VaksServiceClientChannel(System.ServiceModel.ClientBase<PrismUnityApp2.MobileService.IVaksService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = value;
                System.IAsyncResult _result = base.BeginInvoke("GetData", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetData(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMessageDatas(string Latitude, string Longitude, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = Latitude;
                _args[1] = Longitude;
                System.IAsyncResult _result = base.BeginInvoke("GetMessageDatas", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Message> EndGetMessageDatas(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Message> _result = ((System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Message>)(base.EndInvoke("GetMessageDatas", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetToemmeDatas(PrismUnityApp2.MobileService.Toemning toemning, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = toemning;
                System.IAsyncResult _result = base.BeginInvoke("GetToemmeDatas", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> EndGetToemmeDatas(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> _result = ((System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning>)(base.EndInvoke("GetToemmeDatas", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetToemmeDatasByPladsId(int GbsId, System.DateTime date, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = GbsId;
                _args[1] = date;
                System.IAsyncResult _result = base.BeginInvoke("GetToemmeDatasByPladsId", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> EndGetToemmeDatasByPladsId(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning> _result = ((System.Collections.ObjectModel.ObservableCollection<PrismUnityApp2.MobileService.Toemning>)(base.EndInvoke("GetToemmeDatasByPladsId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLoginAndReturnPladsId(string UserName, string Password, double Latitude, double Longitude, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = UserName;
                _args[1] = Password;
                _args[2] = Latitude;
                _args[3] = Longitude;
                System.IAsyncResult _result = base.BeginInvoke("LoginAndReturnPladsId", _args, callback, asyncState);
                return _result;
            }
            
            public PrismUnityApp2.MobileService.AccessData EndLoginAndReturnPladsId(System.IAsyncResult result) {
                object[] _args = new object[0];
                PrismUnityApp2.MobileService.AccessData _result = ((PrismUnityApp2.MobileService.AccessData)(base.EndInvoke("LoginAndReturnPladsId", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IVaksService,
        }
    }
}
